### ISSUE TITLE
minimize() missing 1 required positional argument: 'var_list'

### ISSUE THREAD

**Issue by pygabc1** [gunjanmahindre/Hadamard-Autoencoder#1]
Hi, in order to use Tensorflow 2.x in DeepAI.py I changed 
`self.train_step = tf.train.AdamOptimizer().minimize(self.cost)` into
`self.train_step = tf.optimizers.Adam().minimize(self.cost, var_list = [self.W_list, self.encoding_b_list, self.decoding_b_list]) `.
I referred 
[https://stackoverflow.com/questions/58722591/typeerror-minimize-missing-1-required-positional-argument-var-list].
Am I correct? Or do I have to use ONE of between self.encoding_b_list and self.decoding_b_list ? Or something else?
Thanks.

**Comment by rskarkare** [comment]
Hi,
I believe for tf2.x, you need to include all trainable parameters in the variable list as follows:
self.train_step = tf.optimizers.Adam().minimize(self.cost, var_list = [self.W_list, self.encoding_b_list, self.decoding_b_list])
You might also want to try the following to be compatible with tf 1.x:
Wherever you import tensorflow,
import tensorflow as tf  ,  replace the line with
import tensorflow.compat.v1 as tf

**Comment by gunjanmahindre** [comment]
yes this should work. I also have Tensorflow 2.0 but I import the version 1 as 
import tensorflow.compat.v1 as tf
